/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../src/seed.module';
import * as i2 from '@angular/common';
import * as i3 from '@angular/http';
import * as i4 from '../../src/seed.service';
import * as i5 from 'angular2-virtual-scroll/dist/virtual-scroll';
export const SeedModuleNgFactory:i0.NgModuleFactory<i1.SeedModule> = i0.ɵcmf(i1.SeedModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i3.BrowserXhr,
          i3.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i3.ResponseOptions,i3.BaseResponseOptions,
          ([] as any[])),i0.ɵmpd(5120,i3.XSRFStrategy,i3.ɵb,([] as any[])),i0.ɵmpd(4608,
          i3.XHRBackend,i3.XHRBackend,[i3.BrowserXhr,i3.ResponseOptions,i3.XSRFStrategy]),
          i0.ɵmpd(4608,i3.RequestOptions,i3.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,
              i3.Http,i3.ɵc,[i3.XHRBackend,i3.RequestOptions]),i0.ɵmpd(4608,i4.SeedService,
              i4.SeedService,[i3.Http]),i0.ɵmpd(512,i2.CommonModule,i2.CommonModule,
              ([] as any[])),i0.ɵmpd(512,i3.HttpModule,i3.HttpModule,([] as any[])),
          i0.ɵmpd(512,i5.VirtualScrollModule,i5.VirtualScrollModule,([] as any[])),
          i0.ɵmpd(512,i1.SeedModule,i1.SeedModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvc2hhYW4vYW5ndWxhci1tZXNzYWdlLWhpc3RvcnktbW9kdWxlL3NyYy9zZWVkLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL3NoYWFuL2FuZ3VsYXItbWVzc2FnZS1oaXN0b3J5LW1vZHVsZS9zcmMvc2VlZC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
